# Demonstration of ANGLE functions
 - 20190319
 - MJP

In [1]:
# Standard imports 
import numpy as np 

# classes code 
import angles as ANG


/Users/matthewjohnpayne/anaconda/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


# Main functions in "angles.py"
 - radec2unit
 - unit2radec
 - angle_unitvectors
 - angle_radec

# --------- Test Code Definitions ---------------------

In [8]:

def sample_RADEC():
    ''' 
        Sample RA, DEC arrays for demos
        Degrees
    '''
    
    RA_Array1   = np.array([0.0, 0.0, 90.0, 90.0,   0.0, 180.0,   0.0])
    Dec_Array1  = np.array([0.0,90.0, 90.0,  0.0, -90.0,   0.0,  90.0])
    
    RA_Array2   = np.array([27.0,  0.5,   0.5,  0.0, 90.0,   0.0])
    Dec_Array2  = np.array([-5.0,  5.0,  89.5, 90.0,  0.0, -90.0])

    return RA_Array1,Dec_Array1, RA_Array2, Dec_Array2

def demonstrate_radec2unit():
    '''
        Demonstrate  the conversion of (RA,Dec) to unit vector(s)
    '''
    print('\n Demonstrate  the conversion of (RA,Dec) to unit vector(s)')
    # Get a sample of data
    RA_Array1,Dec_Array1, RA_Array2, Dec_Array2 = sample_RADEC()
    # Convert a single component
    UV = ANG.radec2unit(RA_Array1[0],Dec_Array1[0])
    print("Single Component Input:\n\tRA,Dec Input=(%r,%r)\n\tUnit-Vector Output=%r" % (RA_Array1[0],Dec_Array1[0],UV) )
    # Convert an entire array
    UV_Array = ANG.radec2unit(RA_Array1,Dec_Array1)
    print("Array Input           :\n\tRA,Dec Input=(%r,%r)\n\tUnit-Vector Output=%r" % (RA_Array1,Dec_Array1,UV_Array) )

def demonstrate_unit2radec():
    '''
        Demonstrate  the conversion of unit vector(s) to (RA,Dec)
    '''
    print('\n Demonstrate  the conversion of unit vector(s) to (RA,Dec)')
    # Get a sample of data
    RA_Array1,Dec_Array1, RA_Array2, Dec_Array2 = sample_RADEC()
    # Convert (RA,Dec) to UV
    UV_Array = ANG.radec2unit(RA_Array1,Dec_Array1)
    
    # Convert a single unit-vector back to RA, DEC
    print("\nConversion of single-UV to RA,Dec")
    print("Interim Single UV conversion: uv = ", UV_Array[0])
    RA_output, Dec_output = ANG.unit2radec(UV_Array[0])
    print("\tFinal RA,Dec   = (%r , %r)"%(RA_output, Dec_output))
    
    
    # Convert multiple unit-vectors back to RA,DEC 
    print("\nConversion of multiple UVs to RA,Dec")
    print("\tInterim unit-vectors = %r", UV_Array)
    RA_output, Dec_output = ANG.unit2radec(UV_Array)
    print("\tFinal RA,Dec   = (%r , %r)"%(RA_output, Dec_output))

def demonstrate_radec2unit2radec():
    '''
        Demonstrate that back-and-forth conversion is stable
    '''    
    # Get a sample of data
    RA_Array1,Dec_Array1, RA_Array2, Dec_Array2 = sample_RADEC()
    print("Initial RA,Dec = (%r , %r)"%(RA_Array1,Dec_Array1))
    for i in range(2):
        print("i=",i)
        UV_Array = ANG.radec2unit(RA_Array1,Dec_Array1)
        print("\t UV=",UV_Array)
        RA_Array1,Dec_Array1 = ANG.unit2radec(UV_Array)
        print("\t RA,DEC=",RA_Array1,Dec_Array1)

    
    
def demonstrate_angle_unitvectors():
    '''
        Demonstrate  the calculation of angles between unit vectors
    '''
    print('\n Demonstrate angle between unit vectors')
    # Get a sample of data
    RA_Array1,Dec_Array1, RA_Array2, Dec_Array2 = sample_RADEC()
    # Calculate unit vectors
    uv1 = ANG.radec2unit(RA_Array1,Dec_Array1)
    uv2 = ANG.radec2unit(RA_Array2,Dec_Array2)
    # Angle between 2 single unit vectors
    print("\nSingle unit-vector input ... ")
    print("Input unit vectors = (%r, %r)" % (uv1[0],uv2[0]) )
    print("output = %r [radians] = %r [degrees]" % (ANG.angle_unitvectors(uv1[0],uv2[0]), np.degrees(ANG.angle_unitvectors(uv1[0],uv2[0]))  ) )
    # Angle between 1 single unit vector & an array of other vectors
    print("\n(i)Single unit-vector + (ii)Multiple unit-vector input ... ")
    print("Input unit vectors = (%r, %r)" % (uv1[0],uv2) )
    print("output = %r [radians] = %r [degrees]" % (ANG.angle_unitvectors(uv1[0],uv2), np.degrees(ANG.angle_unitvectors(uv1[0],uv2))  ) )


def demonstrate_angle_radec():
    '''
        Demonstrate  the calculation of angles between (RA,Dec) pairs
    '''
    print('\n Demonstrate angle between RA,Dec components')
    # Get a sample of data
    RA_Array1,Dec_Array1, RA_Array2, Dec_Array2 = sample_RADEC()
    # Angle between 2 single RA,Dec's
    print("\nSingle RA,Dec inputs ... ")
    print("Input (1) = (%r, %r), Input (2) =(%r, %r)" % (RA_Array1[0],Dec_Array1[0],RA_Array2[0],Dec_Array2[0]) )
    print("output = %r [degrees]" % ( ANG.angle_radec(RA_Array1[0],Dec_Array1[0],RA_Array2[0],Dec_Array2[0])  ))
    # Angle between A single RA,Dec & an array of other RA,Dec's
    print("\nSingle+Multiple RA,Dec inputs ... ")
    print("Input (1) = (%r, %r), Input (2) =(%r, %r)" % (RA_Array1[0],Dec_Array1[0],RA_Array2,Dec_Array2) )
    print("output = %r [degrees]" % ( ANG.angle_radec(RA_Array1[0],Dec_Array1[0],RA_Array2,Dec_Array2)  ))





# radec2unit
 - Convert RA,DEC input(s) to unit vector(s)

In [9]:
demonstrate_radec2unit()


 Demonstrate  the conversion of (RA,Dec) to unit vector(s)
Single Component Input:
	RA,Dec Input=(0.0,0.0)
	Unit-Vector Output=array([1., 0., 0.])
Array Input           :
	RA,Dec Input=(array([  0.,   0.,  90.,  90.,   0., 180.,   0.]),array([  0.,  90.,  90.,   0., -90.,   0.,  90.]))
	Unit-Vector Output=array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 6.12323400e-17,  0.00000000e+00,  1.00000000e+00],
       [ 3.74939946e-33,  6.12323400e-17,  1.00000000e+00],
       [ 6.12323400e-17,  1.00000000e+00,  0.00000000e+00],
       [ 6.12323400e-17,  0.00000000e+00, -1.00000000e+00],
       [-1.00000000e+00,  1.22464680e-16,  0.00000000e+00],
       [ 6.12323400e-17,  0.00000000e+00,  1.00000000e+00]])


# unit2radec
 - Convert unit vector(s) to RA,DEC(s)

In [10]:
demonstrate_unit2radec()


 Demonstrate  the conversion of unit vector(s) to (RA,Dec)

Conversion of single-UV to RA,Dec
Interim Single UV conversion: uv =  [1. 0. 0.]
	Final RA,Dec   = (array([0.]) , array([0.]))

Conversion of multiple UVs to RA,Dec
	Interim unit-vectors = %r [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.12323400e-17  0.00000000e+00  1.00000000e+00]
 [ 3.74939946e-33  6.12323400e-17  1.00000000e+00]
 [ 6.12323400e-17  1.00000000e+00  0.00000000e+00]
 [ 6.12323400e-17  0.00000000e+00 -1.00000000e+00]
 [-1.00000000e+00  1.22464680e-16  0.00000000e+00]
 [ 6.12323400e-17  0.00000000e+00  1.00000000e+00]]
	Final RA,Dec   = (array([  0.,   0.,  90.,  90.,   0., 180.,   0.]) , array([  0.,  90.,  90.,   0., -90.,   0.,  90.]))


# Demonstrate that back-and-forth conversion is stable

In [11]:
demonstrate_radec2unit2radec()

Initial RA,Dec = (array([  0.,   0.,  90.,  90.,   0., 180.,   0.]) , array([  0.,  90.,  90.,   0., -90.,   0.,  90.]))
i= 0
	 UV= [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.12323400e-17  0.00000000e+00  1.00000000e+00]
 [ 3.74939946e-33  6.12323400e-17  1.00000000e+00]
 [ 6.12323400e-17  1.00000000e+00  0.00000000e+00]
 [ 6.12323400e-17  0.00000000e+00 -1.00000000e+00]
 [-1.00000000e+00  1.22464680e-16  0.00000000e+00]
 [ 6.12323400e-17  0.00000000e+00  1.00000000e+00]]
	 RA,DEC= [  0.   0.  90.  90.   0. 180.   0.] [  0.  90.  90.   0. -90.   0.  90.]
i= 1
	 UV= [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.12323400e-17  0.00000000e+00  1.00000000e+00]
 [ 3.74939946e-33  6.12323400e-17  1.00000000e+00]
 [ 6.12323400e-17  1.00000000e+00  0.00000000e+00]
 [ 6.12323400e-17  0.00000000e+00 -1.00000000e+00]
 [-1.00000000e+00  1.22464680e-16  0.00000000e+00]
 [ 6.12323400e-17  0.00000000e+00  1.00000000e+00]]
	 RA,DEC= [  0.   0.  90.  90.   0. 180.   0.] [  0.  90.

# angle_unitvectors
 - Calculate the angle between two unit vectors

In [12]:
demonstrate_angle_unitvectors()


 Demonstrate angle between unit vectors

Single unit-vector input ... 
Input unit vectors = (array([1., 0., 0.]), array([ 0.88761598,  0.45226293, -0.08715574]))
output = array([0.47865335]) [radians] = array([27.42481654]) [degrees]

(i)Single unit-vector + (ii)Multiple unit-vector input ... 
Input unit vectors = (array([1., 0., 0.]), array([[ 8.87615975e-01,  4.52262929e-01, -8.71557427e-02],
       [ 9.96156766e-01,  8.69332840e-03,  8.71557427e-02],
       [ 8.72620322e-03,  7.61524218e-05,  9.99961923e-01],
       [ 6.12323400e-17,  0.00000000e+00,  1.00000000e+00],
       [ 6.12323400e-17,  1.00000000e+00,  0.00000000e+00],
       [ 6.12323400e-17,  0.00000000e+00, -1.00000000e+00]]))
output = array([0.47865335, 0.08770061, 1.56207001, 1.57079633, 1.57079633,
       1.57079633]) [radians] = array([27.42481654,  5.02487463, 89.50001904, 90.        , 90.        ,
       90.        ]) [degrees]


# angle_radec
 - Calculate the angle between two sets of RA,DEC

In [13]:
demonstrate_angle_radec()


 Demonstrate angle between RA,Dec components

Single RA,Dec inputs ... 
Input (1) = (0.0, 0.0), Input (2) =(27.0, -5.0)
output = array([27.42481654]) [degrees]

Single+Multiple RA,Dec inputs ... 
Input (1) = (0.0, 0.0), Input (2) =(array([27. ,  0.5,  0.5,  0. , 90. ,  0. ]), array([ -5. ,   5. ,  89.5,  90. ,   0. , -90. ]))
output = array([27.42481654,  5.02487463, 89.50001904, 90.        , 90.        ,
       90.        ]) [degrees]
